/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.TrainerR;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 * GUI class, containing all of the screens for the user to use the application.
 * Also contains code for filling out user information.
 * @author criizzversion4:25
 */
public class TrainR_UI extends javax.swing.JFrame {

    /**
     * Creates new form TrainR_UI
     */
    UserProfile user1;
    CalorieBudget userBudget;
    Goal g;
    UserList userlist = new UserList ();
    Workout WorkoutList = new Workout();
    int ImageCount = 0;
    
    public TrainR_UI() {
        initComponents();
        // create objects for use
        user1 = new UserProfile(); 
        userBudget = new CalorieBudget();
        g = new Goal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeader = new javax.swing.JPanel();
        LabelHeader = new javax.swing.JLabel();
        PanelParent = new javax.swing.JPanel();
        CardLoginPage = new javax.swing.JPanel();
        ButtonLogin = new javax.swing.JButton();
        ButtonNewUser = new javax.swing.JButton();
        LabelUsername = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        TextUsername = new javax.swing.JTextField();
        TextPassword = new javax.swing.JTextField();
        CardNewUserPage = new javax.swing.JPanel();
        ButtonCreateAccount = new javax.swing.JButton();
        ButtonBackFromNewUser = new javax.swing.JButton();
        LabelNewUsername = new javax.swing.JLabel();
        LabelNewPassword = new javax.swing.JLabel();
        LabelNewAge = new javax.swing.JLabel();
        LabelNewHeight = new javax.swing.JLabel();
        LabelNewWeight = new javax.swing.JLabel();
        LabelNewSex = new javax.swing.JLabel();
        LabelNewGoal = new javax.swing.JLabel();
        TextNewUsername = new javax.swing.JTextField();
        TextNewPassword = new javax.swing.JTextField();
        ComboNewAge = new javax.swing.JComboBox<>();
        ComboNewHeightFt = new javax.swing.JComboBox<>();
        LabelNewFt = new javax.swing.JLabel();
        LabelNewIn = new javax.swing.JLabel();
        ComboNewHeightIn = new javax.swing.JComboBox<>();
        ComboNewWeight = new javax.swing.JComboBox<>();
        LabelNewLbs = new javax.swing.JLabel();
        ComboNewSex = new javax.swing.JComboBox<>();
        ComboNewGoal = new javax.swing.JComboBox<>();
        CardStartWorkout = new javax.swing.JPanel();
        ButtonBackFromStartWorkout = new javax.swing.JButton();
        ButtonStartWorkout = new javax.swing.JButton();
        LabelDisplayCalories = new javax.swing.JLabel();
        LabelDisplayUsername = new javax.swing.JLabel();
        LabelDisplayGoal = new javax.swing.JLabel();
        CardWorkout = new javax.swing.JPanel();
        ButtonBackFromWorkout = new javax.swing.JButton();
        ButtonFinishWorkout = new javax.swing.JButton();
        CheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaWorkoutList = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ButtonShowImages = new javax.swing.JButton();
        CardImages = new javax.swing.JPanel();
        LabelImage = new javax.swing.JLabel();
        ButtonBackFromImage = new javax.swing.JButton();
        ButtonPreviousImage = new javax.swing.JButton();
        ButtonNextImage = new javax.swing.JButton();
        LabelImageTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelHeader.setBackground(new java.awt.Color(204, 255, 204));
        PanelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelHeader.setText("TrainR");
        LabelHeader.setToolTipText("");

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelParent.setLayout(new java.awt.CardLayout());

        CardLoginPage.setBackground(new java.awt.Color(153, 153, 255));
        CardLoginPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Page"));
        CardLoginPage.setPreferredSize(new java.awt.Dimension(500, 400));

        ButtonLogin.setText("Login");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        ButtonNewUser.setText("New User?");
        ButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewUserActionPerformed(evt);
            }
        });

        LabelUsername.setText("Username:");

        LabelPassword.setText("Password:");

        javax.swing.GroupLayout CardLoginPageLayout = new javax.swing.GroupLayout(CardLoginPage);
        CardLoginPage.setLayout(CardLoginPageLayout);
        CardLoginPageLayout.setHorizontalGroup(
            CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardLoginPageLayout.createSequentialGroup()
                .addGroup(CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardLoginPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonNewUser))
                    .addGroup(CardLoginPageLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(ButtonLogin)
                        .addGap(0, 387, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(CardLoginPageLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(LabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(TextPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CardLoginPageLayout.setVerticalGroup(
            CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardLoginPageLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsername)
                    .addComponent(TextUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(CardLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPassword)
                    .addComponent(TextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(ButtonLogin)
                .addGap(134, 134, 134)
                .addComponent(ButtonNewUser)
                .addContainerGap())
        );

        PanelParent.add(CardLoginPage, "card3");

        CardNewUserPage.setBackground(new java.awt.Color(255, 255, 204));
        CardNewUserPage.setBorder(javax.swing.BorderFactory.createTitledBorder("New User Page"));
        CardNewUserPage.setPreferredSize(new java.awt.Dimension(500, 400));

        ButtonCreateAccount.setText("Create Account");
        ButtonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateAccountActionPerformed(evt);
            }
        });

        ButtonBackFromNewUser.setText("Back");
        ButtonBackFromNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackFromNewUserActionPerformed(evt);
            }
        });

        LabelNewUsername.setText("Username:");

        LabelNewPassword.setText("Password:");

        LabelNewAge.setText("Age:");

        LabelNewHeight.setText("Height:");

        LabelNewWeight.setText("Weight:");

        LabelNewSex.setText("Sex:");

        LabelNewGoal.setText("Goal:");

        TextNewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNewUsernameActionPerformed(evt);
            }
        });

        ComboNewAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        ComboNewHeightFt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7" }));
        ComboNewHeightFt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNewHeightFtActionPerformed(evt);
            }
        });

        LabelNewFt.setText("ft.");

        LabelNewIn.setText("in.");

        ComboNewHeightIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));

        ComboNewWeight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "216", "217", "218", "219", "220", "221", "222", "223", "224", "225", "226", "227", "228", "229", "230", "231", "232", "233", "234", "235", "236", "237", "238", "239", "240", "241", "242", "243", "244", "245", "246", "247", "248", "249", "250", "251", "252", "253", "254", "255", "256", "257", "258", "259", "260", "261", "262", "263", "264", "265", "266", "267", "268", "269", "270", "271", "272", "273", "274", "275", "276", "277", "278", "279", "280", "281", "282", "283", "284", "285", "286", "287", "288", "289", "290", "291", "292", "293", "294", "295", "296", "297", "298", "299", "300" }));

        LabelNewLbs.setText("lbs.");

        ComboNewSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        ComboNewGoal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Build Muscle", "Increase Endurance", "Lose Weight" }));

        javax.swing.GroupLayout CardNewUserPageLayout = new javax.swing.GroupLayout(CardNewUserPage);
        CardNewUserPage.setLayout(CardNewUserPageLayout);
        CardNewUserPageLayout.setHorizontalGroup(
            CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardNewUserPageLayout.createSequentialGroup()
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardNewUserPageLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(ButtonCreateAccount))
                    .addGroup(CardNewUserPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonBackFromNewUser))
                    .addGroup(CardNewUserPageLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNewUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(LabelNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNewAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNewHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNewWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNewSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNewGoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CardNewUserPageLayout.createSequentialGroup()
                                .addComponent(ComboNewHeightFt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNewFt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboNewHeightIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNewIn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextNewUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextNewPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboNewAge, javax.swing.GroupLayout.Alignment.LEADING, 0, 133, Short.MAX_VALUE))
                            .addGroup(CardNewUserPageLayout.createSequentialGroup()
                                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboNewGoal, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(ComboNewSex, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE)
                                    .addComponent(ComboNewWeight, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNewLbs)))))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        CardNewUserPageLayout.setVerticalGroup(
            CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardNewUserPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNewUsername)
                    .addComponent(TextNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNewPassword)
                    .addComponent(TextNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNewAge)
                    .addComponent(ComboNewAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNewHeight)
                    .addComponent(ComboNewHeightFt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNewFt)
                    .addComponent(ComboNewHeightIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNewIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNewWeight)
                    .addComponent(ComboNewWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNewLbs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNewSex)
                    .addComponent(ComboNewSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardNewUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNewGoal)
                    .addComponent(ComboNewGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(ButtonCreateAccount)
                .addGap(51, 51, 51)
                .addComponent(ButtonBackFromNewUser)
                .addGap(39, 39, 39))
        );

        PanelParent.add(CardNewUserPage, "card2");

        CardStartWorkout.setBackground(new java.awt.Color(255, 0, 153));
        CardStartWorkout.setBorder(javax.swing.BorderFactory.createTitledBorder("Start Workout Page"));
        CardStartWorkout.setPreferredSize(new java.awt.Dimension(500, 400));

        ButtonBackFromStartWorkout.setText("Back");
        ButtonBackFromStartWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackFromStartWorkoutActionPerformed(evt);
            }
        });

        ButtonStartWorkout.setText("Start Workout");
        ButtonStartWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartWorkoutActionPerformed(evt);
            }
        });

        LabelDisplayCalories.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelDisplayCalories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDisplayCalories.setText("Calorie Budget: " + "Get from calculation");

        LabelDisplayUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelDisplayUsername.setText("Test");

        LabelDisplayGoal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelDisplayGoal.setText("Goal: " + "Get from database");

        javax.swing.GroupLayout CardStartWorkoutLayout = new javax.swing.GroupLayout(CardStartWorkout);
        CardStartWorkout.setLayout(CardStartWorkoutLayout);
        CardStartWorkoutLayout.setHorizontalGroup(
            CardStartWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardStartWorkoutLayout.createSequentialGroup()
                .addGroup(CardStartWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardStartWorkoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonBackFromStartWorkout))
                    .addGroup(CardStartWorkoutLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(ButtonStartWorkout))
                    .addGroup(CardStartWorkoutLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(LabelDisplayCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CardStartWorkoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CardStartWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelDisplayUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(LabelDisplayGoal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        CardStartWorkoutLayout.setVerticalGroup(
            CardStartWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardStartWorkoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelDisplayGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(LabelDisplayCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonStartWorkout)
                .addGap(136, 136, 136)
                .addComponent(ButtonBackFromStartWorkout)
                .addContainerGap())
        );

        PanelParent.add(CardStartWorkout, "card4");

        CardWorkout.setBackground(new java.awt.Color(0, 255, 255));
        CardWorkout.setBorder(javax.swing.BorderFactory.createTitledBorder("Workout Page"));
        CardWorkout.setPreferredSize(new java.awt.Dimension(500, 400));

        ButtonBackFromWorkout.setText("Back");
        ButtonBackFromWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackFromWorkoutActionPerformed(evt);
            }
        });

        ButtonFinishWorkout.setText("Finish Workout");
        ButtonFinishWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFinishWorkoutActionPerformed(evt);
            }
        });

        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        TextAreaWorkoutList.setEditable(false);
        TextAreaWorkoutList.setColumns(20);
        TextAreaWorkoutList.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextAreaWorkoutList.setRows(5);
        jScrollPane1.setViewportView(TextAreaWorkoutList);

        jLabel1.setText("Workout Complete:");

        ButtonShowImages.setText("Show Images");
        ButtonShowImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonShowImagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CardWorkoutLayout = new javax.swing.GroupLayout(CardWorkout);
        CardWorkout.setLayout(CardWorkoutLayout);
        CardWorkoutLayout.setHorizontalGroup(
            CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardWorkoutLayout.createSequentialGroup()
                .addGroup(CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardWorkoutLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ButtonShowImages))
                    .addGroup(CardWorkoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonBackFromWorkout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CardWorkoutLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(CheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardWorkoutLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonFinishWorkout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CardWorkoutLayout.setVerticalGroup(
            CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CardWorkoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CardWorkoutLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(ButtonShowImages)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardWorkoutLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonBackFromWorkout)
                            .addComponent(ButtonFinishWorkout)))
                    .addGroup(CardWorkoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(CheckBox1)))
                .addGap(82, 82, 82))
        );

        PanelParent.add(CardWorkout, "card5");

        LabelImage.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        ButtonBackFromImage.setText("Back");
        ButtonBackFromImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackFromImageActionPerformed(evt);
            }
        });

        ButtonPreviousImage.setText("Previous");
        ButtonPreviousImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPreviousImageActionPerformed(evt);
            }
        });

        ButtonNextImage.setText("Next");
        ButtonNextImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNextImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CardImagesLayout = new javax.swing.GroupLayout(CardImages);
        CardImages.setLayout(CardImagesLayout);
        CardImagesLayout.setHorizontalGroup(
            CardImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardImagesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CardImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonPreviousImage)
                    .addComponent(ButtonBackFromImage))
                .addGap(18, 18, 18)
                .addGroup(CardImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardImagesLayout.createSequentialGroup()
                        .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(ButtonNextImage)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(CardImagesLayout.createSequentialGroup()
                        .addComponent(LabelImageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        CardImagesLayout.setVerticalGroup(
            CardImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardImagesLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(ButtonNextImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardImagesLayout.createSequentialGroup()
                .addGroup(CardImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CardImagesLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(ButtonPreviousImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonBackFromImage))
                    .addGroup(CardImagesLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(LabelImageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        PanelParent.add(CardImages, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelParent, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // login button. Check for existing user has not been implemented yet.
        userlist.read_users();
        int uIndex = userlist.findUsername(TextUsername.getText());
        int pIndex = userlist.findPassword(TextPassword.getText());
        if (uIndex >= 0 && uIndex== pIndex) {
            user1.setTo(userlist.getActiveUser(uIndex));
            userBudget.getMaintenance(user1.getAge(), user1.getWeight(), user1.getHeight(), user1.getSex());
            LabelDisplayUsername.setText("User: " + user1.getUser());
            LabelDisplayGoal.setText("Goal: " +user1.getGoal());
            LabelDisplayCalories.setText("Daily Calorie Budget: " + String.valueOf(Math.round(userBudget.getBudget())));
            TextUsername.setText("");
            TextPassword.setText("");
            PanelParent.removeAll();
            PanelParent.add(CardStartWorkout);
            PanelParent.repaint();
            PanelParent.validate();
            g.initWorkout();
        }
        else {
            System.out.println("Incorrect Username and/or password."); // replace with proper error message
        }
        
        //System.out.println(g.printStrengthWorkout());
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void ButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewUserActionPerformed
        // sends user to input new user information form
        PanelParent.removeAll();
        PanelParent.add(CardNewUserPage);
        PanelParent.repaint();
        PanelParent.validate();
    }//GEN-LAST:event_ButtonNewUserActionPerformed

    private void ButtonBackFromNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackFromNewUserActionPerformed
        // return to login screen
        PanelParent.removeAll();
        PanelParent.add(CardLoginPage);
        PanelParent.repaint();
        PanelParent.validate();
    }//GEN-LAST:event_ButtonBackFromNewUserActionPerformed

    private void ButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateAccountActionPerformed
        // when create account is selected, variables are assigned based on values in text boxes
        user1.setUser(TextNewUsername.getText());
        user1.setPassword(TextNewPassword.getText());
        user1.setAge(ComboNewAge.getSelectedItem().toString());
        
        String heightft = ComboNewHeightFt.getSelectedItem().toString();
        String heightin = ComboNewHeightIn.getSelectedItem().toString();
        int height = Integer.parseInt(heightft)*12 + Integer.parseInt(heightin);
        user1.setHeight(height);
        
        user1.setWeight(ComboNewWeight.getSelectedItem().toString());
        
        user1.setSex(ComboNewSex.getSelectedItem().toString());
        
        user1.setGoal(ComboNewGoal.getSelectedItem().toString());
        
        // calculate calorie budget
        userBudget.getMaintenance(user1.getAge(), user1.getWeight(), user1.getHeight(), user1.getSex());
        
        user1.save();
        
        PanelParent.removeAll();
        PanelParent.add(CardStartWorkout);
        LabelDisplayUsername.setText("User: " + user1.getUser());
        LabelDisplayGoal.setText("Goal: " +user1.getGoal());
        LabelDisplayCalories.setText("Daily Calorie Budget: " + String.valueOf(Math.round(userBudget.getBudget())));
        PanelParent.repaint();
        PanelParent.validate();
        g.initWorkout();
    }//GEN-LAST:event_ButtonCreateAccountActionPerformed

    private void ButtonBackFromStartWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackFromStartWorkoutActionPerformed
        PanelParent.removeAll();
        PanelParent.add(CardLoginPage);
        PanelParent.repaint();
        PanelParent.validate();
        g.clearWorkout();
    }//GEN-LAST:event_ButtonBackFromStartWorkoutActionPerformed

    private void ButtonBackFromWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackFromWorkoutActionPerformed
        PanelParent.removeAll();
        PanelParent.add(CardStartWorkout);
        PanelParent.repaint();
        PanelParent.validate();
    }//GEN-LAST:event_ButtonBackFromWorkoutActionPerformed

    private void ButtonFinishWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFinishWorkoutActionPerformed
        // if a checkbox for an exercise is selected, add calories burned for that exercise
        // temporarily set to 100, rework with rework of exercise/workout class
        if(CheckBox1.isSelected()) {
            userBudget.addWorkout(g.getWorkoutCals(user1));
        }
        
        // reset checkboxes before moving to next screen
        CheckBox1.setSelected(false);
        
        PanelParent.removeAll();
        PanelParent.add(CardStartWorkout);
        // recalculate value to display
        LabelDisplayCalories.setText("Daily Calorie Budget: " + String.valueOf(Math.round(userBudget.getBudget())));
        PanelParent.repaint();
        PanelParent.validate();
    }//GEN-LAST:event_ButtonFinishWorkoutActionPerformed

    private void ButtonStartWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartWorkoutActionPerformed
        PanelParent.removeAll();
        PanelParent.add(CardWorkout);
        PanelParent.repaint();
        PanelParent.validate();
        TextAreaWorkoutList.setText(g.printWorkout(user1));

    }//GEN-LAST:event_ButtonStartWorkoutActionPerformed

    private void TextNewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNewUsernameActionPerformed
        
    }//GEN-LAST:event_TextNewUsernameActionPerformed

    private void ComboNewHeightFtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNewHeightFtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboNewHeightFtActionPerformed

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void ButtonShowImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonShowImagesActionPerformed
        
        // diving workouts
        WorkoutList.ArrayList = WorkoutList.ArrayWorkout(TextAreaWorkoutList.getText());
        
        // get image
        ImageIcon icon = new ImageIcon(getClass().getResource("/WorkoutImages/" + WorkoutList.ArrayList[0] + ".png"));
        Image image = icon.getImage();
        int scaledWidth = 441; // change this to the desired width
        int scaledHeight = 341; // change this to the desired height
        Image scaledImage = image.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
        
        // set image
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        LabelImage.setIcon(scaledIcon);
        
        // show new screen
        PanelParent.removeAll();
        PanelParent.add(CardImages);
        PanelParent.repaint();
        PanelParent.validate();
        ImageCount = 0;
        LabelImageTitle.setText(WorkoutList.ArrayList[ImageCount]);
    }//GEN-LAST:event_ButtonShowImagesActionPerformed

    private void ButtonBackFromImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackFromImageActionPerformed
        PanelParent.removeAll();
        PanelParent.add(CardWorkout);
        PanelParent.repaint();
        PanelParent.validate();
    }//GEN-LAST:event_ButtonBackFromImageActionPerformed

    private void ButtonNextImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNextImageActionPerformed

        if (ImageCount > WorkoutList.ArrayList.length - 2){
            
            ImageCount = WorkoutList.ArrayList.length - 1;
        }
        
        else {
            ImageCount = ImageCount + 1;
            ImageIcon icon = new ImageIcon(getClass().getResource("/WorkoutImages/" + WorkoutList.ArrayList[ImageCount] + ".png"));
            Image image = icon.getImage();
            int scaledWidth = 441; // change this to the desired width
            int scaledHeight = 341; // change this to the desired height
            Image scaledImage = image.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);

            // set image
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            LabelImage.setIcon(scaledIcon);
            LabelImageTitle.setText(WorkoutList.ArrayList[ImageCount]);
        }
        
    }//GEN-LAST:event_ButtonNextImageActionPerformed

    private void ButtonPreviousImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPreviousImageActionPerformed

        if (ImageCount < 1){
            
            ImageCount = 0;
        }
        
        else {
            ImageCount = ImageCount - 1;
            ImageIcon icon = new ImageIcon(getClass().getResource("/WorkoutImages/" + WorkoutList.ArrayList[ImageCount] + ".png"));
            Image image = icon.getImage();
            int scaledWidth = 441; // change this to the desired width
            int scaledHeight = 341; // change this to the desired height
            Image scaledImage = image.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);

            // set image
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
            LabelImage.setIcon(scaledIcon);
            LabelImageTitle.setText(WorkoutList.ArrayList[ImageCount]);
        }
    }//GEN-LAST:event_ButtonPreviousImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainR_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainR_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainR_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainR_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainR_UI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBackFromImage;
    private javax.swing.JButton ButtonBackFromNewUser;
    private javax.swing.JButton ButtonBackFromStartWorkout;
    private javax.swing.JButton ButtonBackFromWorkout;
    private javax.swing.JButton ButtonCreateAccount;
    private javax.swing.JButton ButtonFinishWorkout;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JButton ButtonNewUser;
    private javax.swing.JButton ButtonNextImage;
    private javax.swing.JButton ButtonPreviousImage;
    private javax.swing.JButton ButtonShowImages;
    private javax.swing.JButton ButtonStartWorkout;
    private javax.swing.JPanel CardImages;
    private javax.swing.JPanel CardLoginPage;
    private javax.swing.JPanel CardNewUserPage;
    private javax.swing.JPanel CardStartWorkout;
    private javax.swing.JPanel CardWorkout;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JComboBox<String> ComboNewAge;
    private javax.swing.JComboBox<String> ComboNewGoal;
    private javax.swing.JComboBox<String> ComboNewHeightFt;
    private javax.swing.JComboBox<String> ComboNewHeightIn;
    private javax.swing.JComboBox<String> ComboNewSex;
    private javax.swing.JComboBox<String> ComboNewWeight;
    private javax.swing.JLabel LabelDisplayCalories;
    private javax.swing.JLabel LabelDisplayGoal;
    private javax.swing.JLabel LabelDisplayUsername;
    private javax.swing.JLabel LabelHeader;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JLabel LabelImageTitle;
    private javax.swing.JLabel LabelNewAge;
    private javax.swing.JLabel LabelNewFt;
    private javax.swing.JLabel LabelNewGoal;
    private javax.swing.JLabel LabelNewHeight;
    private javax.swing.JLabel LabelNewIn;
    private javax.swing.JLabel LabelNewLbs;
    private javax.swing.JLabel LabelNewPassword;
    private javax.swing.JLabel LabelNewSex;
    private javax.swing.JLabel LabelNewUsername;
    private javax.swing.JLabel LabelNewWeight;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelParent;
    private javax.swing.JTextArea TextAreaWorkoutList;
    private javax.swing.JTextField TextNewPassword;
    private javax.swing.JTextField TextNewUsername;
    private javax.swing.JTextField TextPassword;
    private javax.swing.JTextField TextUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
